In [9]:
#Tensor

In [10]:
import torch

In [11]:
def activation(x):
    "sigmoid activation function"
    return 1 / (1 + torch.exp(-x))

In [12]:
#generate some data
#set the randome seed for expectable
torch.manual_seed(7)

#features are 5 random number variables
features = torch.randn((1,5))

#true weights for true data , random normal value
weights = torch.randn_like(features)

#true bias term
bias = torch.randn((1,1))

In [13]:
#calculate output for this network using weights and bias 
#make labels from out data and true weights
y = activation(torch.sum(features * weights) + bias)
y = activation((features * weights).sum() + bias)

In [14]:
#calculate the output of this network using matrix multiplication
y = activation(torch.mm(features, weights.view(5,1)) + bias)

#weights.view(a, b) will return a new tensor with the same data as weights with size (a,b)

In [15]:
#Stack them up

In [19]:
#generate some data
torch.manual_seed(7)
#features are 3 random normal variables
features = torch.randn((1, 3))

#define the size of each layers in our network
n_input = features.shape[1]
n_hidden = 2
n_output = 1

#weights for inputs to hidden layer
W1 = torch.randn(n_input, n_hidden)
#weights for hidden layer to output layer
W2 = torch.randn(n_hidden, n_output)

#bias tern for hidden and output layer
B1 = torch.randn(1, n_hidden)
B2 = torch.randn(1, n_output)

In [21]:
h = activation(torch.mm(features, W1) + B1)
output = activation(torch.mm(h, W2) + B2)
print(output)

tensor([[0.3171]])


In [22]:
#Numpy to torch and back

In [23]:
import numpy as np
a = np.random.rand(4, 3)
a

array([[0.01527869, 0.30602863, 0.27083076],
       [0.6350257 , 0.97375724, 0.05007834],
       [0.72358349, 0.04641261, 0.39894402],
       [0.60311098, 0.2740784 , 0.90893008]])

In [24]:
b = torch.from_numpy(a)
b

tensor([[0.0153, 0.3060, 0.2708],
        [0.6350, 0.9738, 0.0501],
        [0.7236, 0.0464, 0.3989],
        [0.6031, 0.2741, 0.9089]], dtype=torch.float64)

In [25]:
b.numpy()

array([[0.01527869, 0.30602863, 0.27083076],
       [0.6350257 , 0.97375724, 0.05007834],
       [0.72358349, 0.04641261, 0.39894402],
       [0.60311098, 0.2740784 , 0.90893008]])

In [26]:
#multilpy pytorch tensor by 2, in place
b.mul_(2)

tensor([[0.0306, 0.6121, 0.5417],
        [1.2701, 1.9475, 0.1002],
        [1.4472, 0.0928, 0.7979],
        [1.2062, 0.5482, 1.8179]], dtype=torch.float64)

In [27]:
a

array([[0.03055738, 0.61205725, 0.54166151],
       [1.2700514 , 1.94751448, 0.10015668],
       [1.44716699, 0.09282522, 0.79788803],
       [1.20622195, 0.54815679, 1.81786017]])